version: '3.3'

services:
  user-management-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-management-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms256m -Xmx512m
      # Variables para H2 Database
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      # Configuraci√≥n JWT
      - APP_JWT_SECRET=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      - APP_JWT_EXPIRATION_MINUTES=60
    volumes:
      # Persistir logs si es necesario
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - user-management-network
networks:
  user-management-network:
    driver: bridge

volumes:
  logs-volume:
    driver: local