app:
  email-regex: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
  password-regex: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-minutes: 60
  security:
    public-paths:
      - /api/v1/users
      - /api/v1/auth/login
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /swagger-resources/**
      - /webjars/**
      - /h2-console/**

spring:
  application:
    name: user-management-api
  datasource:
    url: jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
