app:
  email-regex: ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$
  password-regex: ^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*#?&])[A-Za-z\d@$!%*#?&]{8,}$
  jwt:
    secret: ${APP_JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b}
    expiration-minutes: ${APP_JWT_EXPIRATION_MINUTES:60}
  security:
    public-paths:
      - /api/v1/users
      - /api/v1/auth/login
      - /swagger-ui/**
      - /swagger-ui.html
      - /v3/api-docs/**
      - /swagger-resources/**
      - /webjars/**
      - /h2-console/**
      - /actuator/health

spring:
  application:
    name: user-management-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:usersdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}
    driver-class-name: org.h2.Driver
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Configuración de logs para Docker
logging:
  level:
    "[com.nisum.usermanagement]": INFO
    "[org.springframework.security]": WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/user-management-api.log

# Configuración para Docker
server:
  port: 8080
  forward-headers-strategy: framework

# Actuator para healthcheck
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
  health:
    defaults:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html